eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10090/eureka/
server:
  port: 10092
spring:
  application:
    name: eurekaclient
management:
  security:
  #关闭安全验证，否则访问refresh端点会提示权限不足
    enabled: false
