eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10090/eureka/
server:
  port: 10092
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: gues
  application:
    name: eurekaclient
